# Test Url
baseUrl: http://localhost:4000

# Production Url
#baseUrl: http://gamedeveloper.com.br

# Social Media
linkFacebook: https://www.facebook.com/GameDeveloperBlog
linkTwitter: http://www.twitter.com/cicanci
linkTwitterBlog: http://www.twitter.com/BlogGameDev
linkYoutube: https://www.youtube.com/c/BrunoCicanci
linkGithub: https://www.github.com/cicanci

# Blog Settings
title: gamedeveloper
description: Desenvolvimento de jogos por Bruno Cicanci
email: bruno@gamedeveloper.com.br
paginate: 20
permalink: /:title
post_dirs: false

# Build Settings
gems:
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
